import {
  AccountBookFill,
  FacebookOutline,
  GoogleOutline,
  PlusOutline,
  ArrowLeftOutline,
  PlusCircleFill,
  EyeInvisibleFill,
  EyeInvisibleOutline,
  EyeInvisibleTwoTone,
  MenuFoldOutline,
  WhatsAppOutline,
  FacebookFill,
  InstagramOutline,
  MenuUnfoldOutline,
  DownloadOutline,
  ContainerOutline,
  GlobalOutline,
  TeamOutline,
  UserOutline,
  IdcardOutline,
  MailOutline,
  LockOutline,
} from '@ant-design/icons-angular/icons';

import { IconDefinition } from '@ant-design/icons-angular';

export const icons: IconDefinition[] = [
  AccountBookFill,
  FacebookOutline,
  GoogleOutline,
  PlusOutline,
  GlobalOutline,
  ArrowLeftOutline,
  EyeInvisibleOutline,
  DownloadOutline,
  EyeInvisibleTwoTone,
  WhatsAppOutline,
  FacebookFill,
  InstagramOutline,
  IdcardOutline,
  MailOutline,
  PlusCircleFill,
  MenuFoldOutline,
  EyeInvisibleFill,
  LockOutline,
  UserOutline,
  MenuUnfoldOutline,
  ContainerOutline,
  TeamOutline,
];
